// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "bitbucket.org/kushki/usrv-card-control/types"
)

// ICheckCardStatusService is an autogenerated mock type for the ICheckCardStatusService type
type ICheckCardStatusService struct {
	mock.Mock
}

// CheckCardStatus provides a mock function with given fields: checkCardStatusRequest
func (_m *ICheckCardStatusService) CheckCardStatus(checkCardStatusRequest types.CheckCardStatusRequest) types.CheckCardStatusResponse {
	ret := _m.Called(checkCardStatusRequest)

	if len(ret) == 0 {
		panic("no return value specified for CheckCardStatus")
	}

	var r0 types.CheckCardStatusResponse
	if rf, ok := ret.Get(0).(func(types.CheckCardStatusRequest) types.CheckCardStatusResponse); ok {
		r0 = rf(checkCardStatusRequest)
	} else {
		r0 = ret.Get(0).(types.CheckCardStatusResponse)
	}

	return r0
}

// NewICheckCardStatusService creates a new instance of ICheckCardStatusService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICheckCardStatusService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICheckCardStatusService {
	mock := &ICheckCardStatusService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
