// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	events "github.com/aws/aws-lambda-go/events"
	mock "github.com/stretchr/testify/mock"
)

// IRestoreService is an autogenerated mock type for the IRestoreService type
type IRestoreService struct {
	mock.Mock
}

// RestoreDailyRetries provides a mock function with given fields: ctx, event
func (_m *IRestoreService) RestoreDailyRetries(ctx context.Context, event events.SQSEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for RestoreDailyRetries")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, events.SQSEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIRestoreService creates a new instance of IRestoreService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRestoreService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRestoreService {
	mock := &IRestoreService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
