// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// KushkiLogger is an autogenerated mock type for the KushkiLogger type
type KushkiLogger struct {
	mock.Mock
}

// Debug provides a mock function with given fields: tag, v
func (_m *KushkiLogger) Debug(tag string, v interface{}) {
	_m.Called(tag, v)
}

// Error provides a mock function with given fields: tag, v
func (_m *KushkiLogger) Error(tag string, v interface{}) {
	_m.Called(tag, v)
}

// Info provides a mock function with given fields: tag, v
func (_m *KushkiLogger) Info(tag string, v interface{}) {
	_m.Called(tag, v)
}

// Warning provides a mock function with given fields: tag, v
func (_m *KushkiLogger) Warning(tag string, v interface{}) {
	_m.Called(tag, v)
}

// NewKushkiLogger creates a new instance of KushkiLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKushkiLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *KushkiLogger {
	mock := &KushkiLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
